apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo2app
spec:
  selector:
    matchLabels:
      app: demo2app
  replicas: 2
  template:
    metadata:
      labels:
        app: demo2app
    spec:
      containers:
      - name: demo2app
        image: 'bobbybabu007/python-flask-docker-sample:1.1.0'
        ports:
        - containerPort: 5000
