apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  env: uat

commonAnnotations:
  machine-class: 'intel-i5'
  storage-type: 'nvm-ssd'

nameSuffix: '-uat'