apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  env: prod

commonAnnotations:
  machine-class: 'intel-i7'
  storage-type: 'nvm-2-ssd'

nameSuffix: '-prod'