apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  env: dev

commonAnnotations:
  machine-class: 'intel-i3'
  storage-type: 'ssd'

nameSuffix: '-dev'