apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1app
spec:
  selector:
    matchLabels:
      app: demo1app
  replicas: 5
  template:
    metadata:
      labels:
        app: demo1app
    spec:
      containers:
      - name: demo1app
        image: 'nginx:latest'
        ports:
        - containerPort: 80
